// log in as Troels
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "trmo", "Password" : "onetwo3FOUR" }

### // log in as Jakob
POST https://localhost:7130/auth/login
Content-Type: application/json

{ "Username" : "jknr", "Password" : "password" }

### // allow anonymous
GET https://localhost:7130/test/allowanon

### // must be authorized
GET https://localhost:7130/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJhZjExMzZlMi0zZGQwLTQ3ZGMtYTFmYi05ZDg3NTI4Y2RkODAiLCJpYXQiOiIxNS8xMS8yMDIyIDE0OjM2OjI4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJleHAiOjE2Njg1MjY1ODgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.YwH5yEGemNTUbYaQsLiL-VA47h4P5r9yotFp-JBA0iWQP6k6oEcX1k1fO-MKAo9_Xzq2W-A3XHbvkrr8Wq0VzA



###     // policy mustbevia allowed
GET https://localhost:7130/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyMzYwYWZjNC01ZDQ4LTRlNTctOGYxZC0wYmZlZTFkOWM3ZjIiLCJpYXQiOiIwNi8xMC8yMDIyIDExOjE1OjQxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2NjUwNTg1NDEsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.R1pVBYWQyX_u6W6jJKf2fyVHJvtum3CDgQP3X3otDEI7fQNKZ2yMMA1Pq2Pe5WujGuO0R8nNuqSnVrmL7r8Thg

###    // manual checking MustBeTeacher
GET https://localhost:7130/test/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkY2JlNTU4Yi1hZjBlLTRmNWUtYWIyNC0wNjBiYzUyZWUxNTkiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQ1OjQ4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4NjkxNDgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.3CmYYv_IN9VKHJCLVhyU_y-NNuXO38_TfIoypLdLTTa9QAEbSLdO9h9e2RHIvEIcqJBXScKTLBxwPhihj0obwA





